from pathlib import Path
import json,csv,html,collections
out=Path('outputs/Shell10-Catalog');d=json.loads((out/'shell-settings.json').read_text(encoding='utf-8'))
e=json.loads((out/'explorer10-code-evidence.json').read_text(encoding='utf-8'))
bindings={'SystemSettings_Taskbar_Lock':['TaskbarSizeMove'],'SystemSettings_Taskbar_Location':['StuckRects3'],'SystemSettings_Taskbar_GlommingPrimary':['TaskbarGlomLevel'],'SystemSettings_Taskbar_GlommingSecondary':['MMTaskbarGlomLevel'],'SystemSettings_Taskbar_MultiMon':['MMTaskbarEnabled'],'SystemSettings_Taskbar_MultiMonTaskbarMode':['MMTaskbarMode'],'SystemSettings_Taskbar_SmallButtons':['TaskbarSmallIcons'],'SystemSettings_Taskbar_PeekPreviewDesktop':['DisablePreviewDesktop']}
for x in d['settings']:
 x['codeReferences']=[{'name':t,'source':e['source'],'matches':e['registryNameReferences'][t]} for t in bindings.get(x['id'],[]) if e['registryNameReferences'].get(t)]
 if x['id']=='SystemSettings_Taskbar_Lock':x['notes']+=' В функции IsSizeMoveEnabled: политика LockTaskbar блокирует изменение размера/положения; иначе читается Explorer\\Advanced\\TaskbarSizeMove. При 1 перемещение разрешено. Проверено чтением кода, не экспериментальной записью.'
 if x['id']=='SystemSettings_Taskbar_Location':x['notes']+=' Explorer читает и записывает бинарную структуру StuckRects3\\Settings. Структура содержит состояние и геометрию; менять один байт без проверки версии, мониторов и DPI нельзя считать готовой реализацией.'
(out/'shell-settings.json').write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['Каталог настроек оболочки Windows 10','177 пунктов: 81 запись индекса Windows 10; 23 классических параметра папок по схеме хоста Windows 11; 73 дополнения по интерфейсу.','Это инвентаризация для разработки. Применение настроек в Windows 11 пока не проверено.','Индекс поиска содержит условные и экспериментальные записи. Поэтому это не доказанный перечень всех работающих переключателей Windows 10.','']
for category in d['metadata']['byCategory']:
 lines+=['',category.upper()]
 for x in d['settings']:
  if x['category']==category:lines.append('- '+x['name']+' ['+x['id']+']')
lines+=['','МЕХАНИЗМЫ ДЛЯ ПРИЛОЖЕНИЯ','Для параметров папок доступны SHGetSetSettings и описания Explorer\\Advanced\\Folder.','Персонализацию нужно применять через соответствующие Windows API; настройки представления папок относятся к конкретной папке.','Старый Explorer читает TaskbarSizeMove, TaskbarGlomLevel, MMTaskbarMode/Enabled и StuckRects3. Ссылки на строки кода находятся в JSON.','Перед реализацией записи требуется проверка формата значений, действующих политик, способа обновления интерфейса и восстановления прежнего состояния.','Функции меню Пуск, живых плиток, Новости и интересы, Cortana и режима планшета могут зависеть от компонентов Windows 10, отсутствующих в Windows 11.','Скрытые флаги функций, все групповые политики и расширения сторонних программ не представлены как отдельные настройки.','','Источники документации:']+d['metadata']['sources']
(out/'List.txt').write_text('\n'.join(lines),encoding='utf-8-sig')
# Portable catalog with no settings-write actions or external dependencies.
payload=json.dumps(d,ensure_ascii=False).replace('</','<\\/')
page='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Каталог оболочки Windows 10</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#202329;font:15px Segoe UI,Arial,sans-serif}header{background:#fff;padding:26px 5vw;border-bottom:1px solid #d9dde4}h1{font-size:26px;margin:0 0 9px}p{line-height:1.55;margin:8px 0;color:#515c6b}main{max-width:1200px;margin:auto;padding:22px}.tools{display:flex;gap:12px;flex-wrap:wrap;position:sticky;top:0;background:#f5f6f8;padding:12px 0;z-index:1}input,select{font:inherit;padding:11px;border:1px solid #bcc5d0;border-radius:6px;background:white}input{flex:1;min-width:230px}.count{padding:8px 0 15px;color:#566175}.card{background:white;border:1px solid #dbe0e7;border-radius:8px;padding:16px;margin-bottom:10px}.tag{color:#0069b5;font-size:12px;font-weight:600}.name{font-size:17px;font-weight:600;margin:6px 0}.id{font-size:12px;color:#647181;overflow-wrap:anywhere}summary{cursor:pointer;color:#0069b5;margin-top:12px}pre{white-space:pre-wrap;word-break:break-word;font:12px Consolas,monospace;background:#f4f6fa;padding:12px}a{color:#0069b5}.notice{border-left:3px solid #d49221;padding-left:12px;max-width:1040px}footer{padding:20px 0;color:#697482}@media(max-width:600px){header{padding:20px}main{padding:12px}select{width:100%}}
</style><header><h1>Оболочка Windows 10 — каталог настроек</h1><p>Панель задач · Пуск · Рабочий стол · Проводник</p><p class="notice">177 пунктов для разработки своего приложения. 81 запись из индекса Windows 10, 23 определения параметров папок на Windows 11, 73 дополнения. Применение не проверено; экспериментальные функции могут быть недоступны.</p></header><main><div class="tools"><input id="search" type="search" placeholder="Найти настройку, ID или обработчик" aria-label="Поиск"><select id="category" aria-label="Раздел"><option value="">Все разделы</option></select><select id="origin" aria-label="Источник"><option value="">Все источники</option><option value="SystemSettings">Индекс Windows 10</option><option value="FolderOptions">Параметры папок на хосте</option><option value="Supplement">Дополнения интерфейса</option></select></div><div class="count" id="count" aria-live="polite"></div><div id="cards"></div><footer>Каталог ничего не изменяет в Windows. Полный исходный индекс содержит 1131 запись.<p><a href="shell-settings.json">JSON для приложения</a> · <a href="shell-settings.csv">CSV</a> · <a href="List.txt">Текстовый список</a></p></footer></main><script id="data" type="application/json">DATA</script><script>
const data=JSON.parse(document.getElementById('data').textContent);const search=document.getElementById('search'),category=document.getElementById('category'),origin=document.getElementById('origin');
Object.keys(data.metadata.byCategory).sort((a,b)=>a.localeCompare(b,'ru')).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c+' ('+data.metadata.byCategory[c]+')';category.append(o)});
function selectRows(){const q=search.value.toLocaleLowerCase('ru').trim();return data.settings.filter(s=>(!category.value||s.category===category.value)&&(!origin.value||s.id.startsWith(origin.value))&&(!q||[s.name,s.id,s.category,s.hostHandler,s.notes].join(' ').toLocaleLowerCase('ru').includes(q)))}
function el(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
function render(){const rows=selectRows(),cards=document.getElementById('cards');cards.replaceChildren();document.getElementById('count').textContent='Показано: '+rows.length+' из '+data.settings.length;for(const s of rows){const c=el('article','','card');c.append(el('div',s.category,'tag'),el('div',s.name,'name'),el('div',s.id,'id'));const detail=el('details','');detail.append(el('summary','Источник и механизм'),el('p',s.verification),el('p','Название: '+s.nameSource));if(s.hostHandler)detail.append(el('p','Обработчик на Windows 11: '+s.hostHandler+'; тип: '+s.hostType));if(Object.keys(s.registry).length)detail.append(el('pre',JSON.stringify(s.registry,null,2)));if(s.codeReferences.length)detail.append(el('pre',JSON.stringify(s.codeReferences,null,2)));detail.append(el('p',s.notes));if(s.evidence.length)detail.append(el('pre',JSON.stringify(s.evidence,null,2)));c.append(detail);cards.append(c)}}
search.addEventListener('input',render);category.addEventListener('change',render);origin.addEventListener('change',render);render();
</script></html>'''.replace('DATA',payload)
(out/'Catalog.html').write_text(page,encoding='utf-8')
print('catalog',len(d['settings']),'sources',collections.Counter(x['id'].split('.')[0] if not x['id'].startswith('SystemSettings') else 'SystemSettings' for x in d['settings']))
# Semantic checks: every entry identified, no duplicate IDs, original records retained.
assert len({x['id'] for x in d['settings']})==len(d['settings'])
assert all(x['name'] and x['category'] for x in d['settings'])
assert len(json.loads((out/'all-settings-index.json').read_text(encoding='utf-8')))==1131
assert all('\ufffd' not in x['name'] for x in d['settings'])
assert any(x['id']=='SystemSettings_Taskbar_Location' and x['codeReferences'] for x in d['settings'])
print('catalog checks OK')
