from pathlib import Path
import json,uuid,hashlib
root=Path.cwd();guid=uuid.UUID('acbe964b-0eed-4d11-9ca9-fdeb63598d2e').bytes_le
mods={}
for name in ['SystemSettings.dll','SystemSettingsViewModel.Desktop.dll']:
 p=root/'outputs/Windows10-Components/Image/4/Windows/ImmersiveControlPanel'/name;b=p.read_bytes(); offsets=[];at=0
 while (at:=b.find(guid,at))>=0:offsets.append(hex(at));at+=16
 mods[name]={'sha256':hashlib.sha256(b).hexdigest(),'environmentInterfaceGUIDFileOffsets':offsets}
report={'MRT':{'originalWrongXBFBytes':2090,'correctXBFBytes':35934,'correctXBFSHA256':'61212b95dde521924c56925b14718473ea3dd5d88a95d8d74e581c7311eecdd0','actualTrial':'broker-settings-60d029f0a863.log','fix':'native genuine IMrtResourceManager InitializeForFile explicit old Threshold PRI, only process current-app XAML MRT factory route redirected'},'publicEnvironmentABI':{'IID':'acbe964b-0eed-4d11-9ca9-fdeb63598d2e','sameIIDOldHost':True,'delegateIID':'c30dfc1c-e392-4d02-ae09-a8ebf08cbc75','oldMethods':{'6':'IsSettingApplicable','7':'IsSettingAccessible','8':'IsSettingTextDynamic','9':'add_SettingsEnvironmentChanged','10':'remove_SettingsEnvironmentChanged'},'hostMethods':{'6':'IsSettingApplicable','7':'IsSettingAccessible','8':'IsSettingTextDynamic','9':'IsSettingGlyphDynamic','10':'add_SettingsEnvironmentChanged','11':'remove_SettingsEnvironmentChanged'},'actualAddFailureCallsite':'oldVM4b0e4 displacement at4b0e7','passedAfterAddPatch':'broker-settings-8bce518364a8.log','removeAudit':'No native-interface +0x50 call in oldVM SettingsEnvironment region4a528..4c528; second +0x48 belongs ICoreWindow.Dispatcher and is intentionally unchanged; not a whole binary semantic proof'},'nextFailure':{'oldVMCallsite':'4b9ba lambda UseAlternateText wrapper calls native interface slot8','HRESULT':'8002802b','fatal':'SettingsEnvironmentWrapper.cpp54','firstSettingIDCapture':'SettingsPageGroupNetwork','firstSettingIDNotProvenFailed':True,'counterEvidence':'Direct native/old desktop environment and native DataModel default/per-user factory probes in Settings identity all return real S_OK FALSE for SettingsPageGroupNetwork; next diagnostic must correlate ID and HRESULT'},'nextDiagnostic':{'helper':'Lab/SettingsDynamicTextDiag/SettingsDynamicTextDiag.dll','guard':'oldVM SHA + entry4b990 prologue16 bytes','behavior':'same lambda captures, same native slot8 args, same returned value; genuine old __abi_WinRTraiseException HRESULT on failure; logs only bounded system Settings ID and actual HRESULT','ownNonUITest':'own-init-probe.log PASS','actualTrialPendingRootGo':True},'modules':mods,'privateEnvironmentABI':'settings-private-environment-abi.json','oldDatamodelFactory':'settings-old-datamodel-factory.log full LoadLibrary + GetActivationFactory/QIStatics PASS only, no UI','registrationFact':'SettingsEnvironmentDatabaseServer ActivationType0 inproc native Datamodel. Server name alone is not out-of-process evidence.'}
(root/'work/settings-current-contract-notes.json').write_text(json.dumps(report,indent=2),encoding='utf8');print(mods)
